services:
  storybook:
    image: andromeda-storybook
    build: 
      context: .
      dockerfile: ./docker/storybook.Dockerfile
    ports:
      - 6006:6006
  
  frontend:
    image: andromeda-frontend
    build: 
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - 3000:3000